theme = "congo"
title = '物語の設計図：現代小説構築の技術と実践'

# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "/"
defaultContentLanguage = "ja"

enableRobotsTXT = true
summaryLength = 100

googleAnalytics = "G-YVE4B0V17G"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true

